spring:
  application:
    name: discovery-service

server:
  port: 8083

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8083}/eureka/