spring:
  application:
    name: product-service
  mvc:
    pathmatch:
       matching-strategy: ant_path_matcher
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8083}/eureka/