spring:
  application:
    name: client-service
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8083}/eureka/